# Usamos una imagen ligera de Python
FROM python:3.10-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalamos dependencias del sistema necesarias para MySQL (pymysql/mysqlclient)
RUN apt-get update && apt-get install -y \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copiamos solo el archivo de requerimientos primero (para aprovechar la caché de Docker)
COPY requirements.txt .

# Instalamos las librerías
RUN pip install --no-cache-dir -r requirements.txt

# Exponemos el puerto de Flask
EXPOSE 5000

# Comando para correr Flask en modo desarrollo
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]