"""empty message

Revision ID: 250db2abec58
Revises: aa65595a7441
Create Date: 2026-05-02 21:57:25.310599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250db2abec58'
down_revision = 'aa65595a7441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesiones_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_caja', sa.String(length=20), nullable=True))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_caja', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('tipo_caja')

    with op.batch_alter_table('sesiones_caja', schema=None) as batch_op:
        batch_op.drop_column('tipo_caja')

    # ### end Alembic commands ###
