"""empty message

Revision ID: 38742e985ed2
Revises: 
Create Date: 2025-12-29 18:33:41.436854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38742e985ed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsors')
    op.drop_table('ligas')
    op.drop_table('direcciones_envio')
    op.drop_table('temporadas')
    op.drop_table('movimientos_inventario')
    op.drop_table('jugadores')
    with op.batch_alter_table('config_integraciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('plataforma'))

    op.drop_table('config_integraciones')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id_venta'))

    op.drop_table('facturas')
    op.drop_table('estados_envio')
    op.drop_table('equipos')
    op.drop_table('materiales')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('categorias_especificas', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('telefono')

    with op.batch_alter_table('detalle_reserva', schema=None) as batch_op:
        batch_op.alter_column('precio_historico',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('detalles_ventas', schema=None) as batch_op:
        batch_op.alter_column('id_variante',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('id_rol',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha_ingreso',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('notas_credito', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('producto_variantes', schema=None) as batch_op:
        batch_op.alter_column('talla',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('tiendanube_variant_id',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('sincronizado_nube')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('tiendanube_id',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('productos_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('id_material')

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('monto_sena',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('saldo_restante',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('roles_empleados', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('roles_empleados', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('saldo_restante',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('monto_sena',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_material', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('productos_ibfk_3'), 'materiales', ['id_material'], ['id_material'])
        batch_op.alter_column('tiendanube_id',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('producto_variantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sincronizado_nube', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.alter_column('tiendanube_variant_id',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('talla',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('notas_credito', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fecha_ingreso',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('id_rol',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('detalles_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('precio_unitario',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('id_variante',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('detalle_reserva', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('precio_historico',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.DATE(), server_default=sa.text('(curdate())'), nullable=True))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('categorias_especificas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.TEXT(), nullable=True))

    op.create_table('materiales',
    sa.Column('id_material', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_material'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('equipos',
    sa.Column('id_equipo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ciudad', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id_liga', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_sponsor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_liga'], ['ligas.id_liga'], name='equipos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_equipo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estados_envio',
    sa.Column('id_estado_envio', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_estado_envio'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('facturas',
    sa.Column('id_factura', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_venta', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_emision', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('total', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], name=op.f('facturas_ibfk_1')),
    sa.PrimaryKeyConstraint('id_factura'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id_venta'), ['id_venta'], unique=True)

    op.create_table('config_integraciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plataforma', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('access_token', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('app_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ultimo_sync', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('config_integraciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('plataforma'), ['plataforma'], unique=True)

    op.create_table('jugadores',
    sa.Column('id_jugador', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('apellido', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('posicion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_equipo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipos.id_equipo'], name=op.f('jugadores_ibfk_1')),
    sa.PrimaryKeyConstraint('id_jugador'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('movimientos_inventario',
    sa.Column('id_movimiento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_variante', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_movimiento', mysql.ENUM('Ingreso', 'Egreso'), nullable=True),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('motivo', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variantes.id_variante'], name=op.f('movimientos_inventario_ibfk_1')),
    sa.PrimaryKeyConstraint('id_movimiento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('temporadas',
    sa.Column('id_temporada', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('anio_inicio', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anio_fin', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_temporada'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('direcciones_envio',
    sa.Column('id_direccion', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ciudad', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('provincia', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('codigo_postal', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=100), server_default=sa.text("'Argentina'"), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name=op.f('direcciones_envio_ibfk_1')),
    sa.PrimaryKeyConstraint('id_direccion'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ligas',
    sa.Column('id_liga', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pais', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_liga'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sponsors',
    sa.Column('id_sponsor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_sponsor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
