"""empty message

Revision ID: aa65595a7441
Revises: 
Create Date: 2026-04-30 17:54:41.561484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa65595a7441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('categorias_especificas',
    sa.Column('id_categoria_especifica', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria_especifica')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('dni', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('gastos',
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.create_table('metodos_pago',
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_metodo_pago')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('importante', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_credito',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_nota'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('presupuestos',
    sa.Column('id_presupuesto', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento_porcentaje', sa.Integer(), nullable=True),
    sa.Column('total_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_presupuesto')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_sena', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saldo_restante', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'retirada', 'cancelada'), nullable=True),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('roles_empleados',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('sesiones_caja',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_ventas_sistema', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('empleados',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles_empleados.id_rol'], ),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movimientos_caja',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones_caja.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_categoria_especifica', sa.Integer(), nullable=True),
    sa.Column('tiendanube_id', sa.String(length=50), nullable=True),
    sa.Column('sincronizado_web', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_categoria_especifica'], ['categorias_especificas.id_categoria_especifica'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id_metodo_pago'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalle_nota_credito',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_nota'], ['notas_credito.id_nota'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('producto_variantes',
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('codigo_sku', sa.String(length=50), nullable=True),
    sa.Column('tiendanube_variant_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_variante'),
    sa.UniqueConstraint('codigo_sku')
    )
    op.create_table('ventas_pagos',
    sa.Column('id_venta_pago', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id_metodo_pago'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_venta_pago')
    )
    op.create_table('detalle_presupuesto',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_presupuesto', sa.Integer(), nullable=True),
    sa.Column('id_variante', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('producto_nombre', sa.String(length=255), nullable=True),
    sa.Column('talle', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_presupuesto'], ['presupuestos.id_presupuesto'], ),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variantes.id_variante'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('detalle_reserva',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_historico', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variantes.id_variante'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('detalles_compra',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variantes.id_variante'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('detalles_ventas',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=True),
    sa.Column('producto_nombre', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variantes.id_variante'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('inventario',
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_deposito', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variantes.id_variante'], ),
    sa.PrimaryKeyConstraint('id_inventario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario')
    op.drop_table('detalles_ventas')
    op.drop_table('detalles_compra')
    op.drop_table('detalle_reserva')
    op.drop_table('detalle_presupuesto')
    op.drop_table('ventas_pagos')
    op.drop_table('producto_variantes')
    op.drop_table('detalle_nota_credito')
    op.drop_table('ventas')
    op.drop_table('productos')
    op.drop_table('movimientos_caja')
    op.drop_table('empleados')
    op.drop_table('compras')
    op.drop_table('sesiones_caja')
    op.drop_table('roles_empleados')
    op.drop_table('reservas')
    op.drop_table('proveedores')
    op.drop_table('presupuestos')
    op.drop_table('notas_credito')
    op.drop_table('notas')
    op.drop_table('metodos_pago')
    op.drop_table('gastos')
    op.drop_table('clientes')
    op.drop_table('categorias_especificas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
